spring.application.name=taskmanager
jwt.secret=${JWT_SECRET:defaultDevSecretThatShouldBeOverridden1234567890SecretKeyLongEnough}

spring.datasource.url=jdbc:postgresql://localhost:5432/taskmanager
spring.datasource.username=admin
spring.datasource.password=adminpass

# Modo rígido de produção
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false

spring.liquibase.enabled=true
spring.liquibase.changelog=classpath:db/changelog/db.changelog-master.xml