spring.application.name=taskmanager
jwt.secret=${JWT_SECRET:defaultDevSecretThatShouldBeOverridden1234567890SecretKeyLongEnough}

spring.datasource.url=jdbc:postgresql://localhost:5432/taskmanager
spring.datasource.username=taskuser
spring.datasource.password=taskpass
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false

spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false


spring.output.ansi.enabled=ALWAYS
logging.pattern.console=%clr(%d{HH:mm:ss.SSS}){faint} %clr(%-5level) %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n%wEx

spring.liquibase.enabled=true
spring.liquibase.changelog=classpath:db/changelog/db.changelog-main.yaml

springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

logging.level.com.unisinos=DEBUG
logging.level.org.liquibase=INFO